### ISSUE TITLE
exe下载链接没看到

### ISSUE THREAD

**Issue by AKIRAasf** [dawn-lc/IwaraDownloader#2]
**您的功能请求是否与问题有关？请描述。**

对问题的清晰简明描述。例如，我总是感到沮丧，因为...

**描述您想要的解决方案**

对您期望发生的结果进行清晰简明的描述。

**描述您已考虑过的替代方案**

对您考虑过的任何替代解决方案或功能进行清晰简明的描述。

**其他信息**

在此处添加有关功能请求的任何其他上下文信息或截图。

**Comment by dawn-lc** [comment]
https://github.com/dawn-lc/IwaraDownloader/releases/
