### ISSUE TITLE
[BUG]检测到不兼容配置文件，进入i站后也没有悬浮窗和对应复选框

### ISSUE THREAD

**Issue by fortunate521** [dawn-lc/IwaraDownloader#6]
如题，
<img width="449" alt="屏幕截图 2023-12-20 211027" src="https://github.com/dawn-lc/IwaraDownloader/assets/107742529/c398c46e-d524-4b28-9381-a2de24feb23d">

**Comment by fortunate521** [comment]
请问这个如何重新配置，删除重下几次脚本依旧会提醒

**Comment by dawn-lc** [comment]
https://github.com/dawn-lc/IwaraDownloadTool/issues/new/choose
脚本问题请前往脚本所在项目进行反馈，谢谢。
